@url = http://localhost:3000/tarefas

GET {{url}}
###
GET {{url}}/1

###
POST {{url}}
Content-Type: application/json

{
    "titulo" : "Teste"
}

###
PUT {{url}}/2
Content-Type: application/json

{
    "titulo": "Registro alterado",
    "concluida": true
}

###
DELETE {{url}}/2